google/zx

README.md

> Not seeing a real need for an issue. It can be discussed (or dismissed ;)) here.

Fix incorrect sentence on README

---

README.md

Fixes some verbiage issues in README.md.
---
Didn't open an issue due to not thinking it will be necessary for this.

Fix README verbiage

---

package.json

Hey @antonmedv , thanks for the awesome work here. I open this PR for adding NodeJS version checking and updating `engines` in `package.json`.
Since we are using ESM, I specified the NodeJS version require as upper than v12.12.0 for now.
See: 
- [Node v12.12.0: ESM supporting ](https://nodejs.org/dist./v12.12.0/docs/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm)

chore: add node engines require and version check

---

README.md
index.d.ts
index.mjs
zx.mjs

`sleep` is a useful function to write many scripts, and can be easily wrapped from `promisify(setTimeout)`

Add a builtin util function sleep

---

README.md

Various grammar tweaks and sentence improvements to make it read more naturally.
Also added a short byline at the top.

Copyedit readme file

---

README.md
test.mjs
zx.mjs

feat: add legacy `require` API to global

---

test.mjs

Update to test.mjs to treat non-zero cat exit values as errors

---

test.mjs

test: check ts-files processing

---

index.d.ts
package.json
zx.mjs

fix(types): add missed `fetch` declaration, disable `dom` definitions on ts compile

---

README.md

Issues associated with Nodejs version appear regularly. It might be worth making this requirement more clear.
https://github.com/google/zx/issues/122
https://github.com/google/zx/issues/132
https://github.com/google/zx/issues/56

docs(readme): describe requirements

---

README.md
index.mjs

feat: store verbose flag for each promise

---

index.mjs

fix: update 'quote' function regex

---

zx.mjs

fix: trim query string to resolve correct script extension

---

README.md

Update Node version requirement.

---

README.md

Just some small readme improvements

Fix typo and bad phrasing in main README

---

package-lock.json
package.json

fix(test): add a pre-test script to build

---

README.md
index.mjs

This adds another wrapper to disable verbose output on a specific command
Fixes #312

Quiet commands on a per invocation basis

---

index.d.ts

Fixes #331
- [✓] Tests pass
- [ n/a] Appropriate changes to README are included in PR

added missing type declaration for

---

package.json

Update node-fetch to properly handle bom in responses
https://github.com/node-fetch/node-fetch/releases/tag/v3.2.3

chore(deps): update node-fetch to v3.2.3

---

package.json

fix: include `src` to pkg files

---

examples/background-process.mjs

Update serve port from 5000 to 3000.
https://github.com/vercel/serve/pull/680

chore: change example serve port to 3000

---

examples/backup-github.mjs

```
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported
```

docs: update backup-github example

---

.github/workflows/test.yml
README.md
src/context.ts
src/core.ts
src/experimental.ts
test/experimental.test.js
test/index.test.js

refactor: simplify ctx API

---

test/index.test.js

test: check that `p.inherit` does not change the origin promise

---

src/context.ts
src/core.ts

fix(types): declare $ type eхplicitly

---

package.json
test/util.test.js

test: add util tests

---

package.json

test: protect env.PATH from npm/node/yarn runner side-effects

---

src/util.ts
test/util.test.js

feat: improve duration parser

---

src/core.ts
src/globals.ts
test/global.test.js

fix: root ctx should be singleton, rm redundant syncCwd after within

---

README.md

Thanks for this very cool tool!

Fix typos, polish grammar, remove trailing spaces

---

package.json

Hello there 👋🏻 
I did this change according to the issue related, it may help

Add typeVersions for type definitions fixes #462

---

src/core.ts
test/core.test.js

fix: omit fn prototype methods in $ proxy

---

src/core.ts
test-d/core.test-d.ts
test-d/experimental.test-d.ts
test/core.test.js

```js
async function each(ps) {
for (let p of ps) {
p.halt()
}
for (let p of ps) {
await p.run()
}
}
await each([$`say Hello`, $`say World`])
```

Add halt()

---

src/cli.ts
src/core.ts
src/deps.ts
src/goods.ts
test/deps.test.js

fix: handle more require/import api use cases on parsing

---

README.md

docs: add custom logger example

---

docs/markdown.md
src/cli.ts

Fixes #578
> It's a good idea to open an issue first for discussion.

Support ~~~ syntax in md

---

src/globals.ts

Fixes #<issue_number_goes_here>
> It's a good idea to open an issue first for discussion.

fix: `zx/globals` missing type

---

src/deps.ts
test/deps.test.js

Fixes #603
> It's a good idea to open an issue first for discussion.

add . to nameRegex

---

test/cli.test.js

test(cli): fix flaky test

---

src/deps.ts
test/deps.test.js

fix(deps): relax pkg name pattern to comply with npm pkg name validation

---

.github/workflows/test.yml
package-lock.json
package.json
test/all.test.js
test/cli.test.js
test/core.test.js
test/deps.test.js
test/extra.test.js
test/global.test.js
test/goods.test.js
test/package.test.js
test/util.test.js
test/win32.test.js

As a part of deps revision/reduction plan

test: migrate to native node:test

---

tsconfig.json

build(tsconfig): remove `compilerOptions.lib` dom

---

src/core.ts

```ts
import { spawn, spawnSync, StdioNull, StdioPipe } from 'node:child_process'
// ...
export const defaults: Options = {
// ...
spawn,
spawnSync,
log,
}
```

feat: provide `spawnSync` configuration

---

package-lock.json
package.json
scripts/build-dts.mjs
src/core.ts
src/goods.ts
test/fixtures/no-extension

chore: up deps

---

examples/parallel.mjs
src/core.ts
test/core.test.js

test: fix flaky cd test

---

src/goods.ts

fix(spinner): handle 0 tty cols case

---

src/util.ts
test/util.test.js

fix: restore pieces pads in `normalizeMultilinePieces`

---

package-lock.json
package.json
src/core.ts

https://github.com/oven-sh/bun/issues/8787

fix: additional `process.kill` fallback for bun

---

package-lock.json
package.json
src/core.ts
test/core.test.js
test/fixtures/js-project/package-lock.json

closes #771
```ts
import {$} from 'zx'
await $({stdio: 'inherit'})`ls`
```

feat: add `stdio` option

---

src/core.ts
test/core.test.js

feat: let `detached` opt be configurable

---

src/core.ts
test/core.test.js
test/fixtures/js-project/package-lock.json

test: check preset helpers

---

.github/workflows/check.yml
.github/workflows/test.yml
package-lock.json
package.json
test/fixtures/js-project/package-lock.json

* esbuild → 0.21.0
* madge → 7.0.0
Added Nodejs v22 to test matrix since https://github.com/nodejs/node/issues/52682 was resolved

build: update esbuild to v0.21.0

---

package-lock.json
package.json

node.engine 12.0.0 → 12.17.0
https://nodejs.org/api/async_context.html#class-asynclocalstorage

chore: fix node engine requirement

---

.github/workflows/test.yml
package-lock.json
package.json
scripts/build-js.mjs
scripts/deno.polyfill.js
src/globals.ts
test/fixtures/js-project/package-lock.json
test/smoke/deno.test.js

fix: provide compat with deno

---

test/core.test.js

test: refactor core tests, add scopes

---

.github/workflows/test.yml
scripts/build-js.mjs
scripts/deno.polyfill.js

feat: adapt mjs bundle for nodejs v12

---

src/cli.ts

refactor: export cli inners

---

package-lock.json
package.json

deps: update zurk to v0.2.0

---

api.md

chore: fix fetch API description

---

src/globals.ts

```js
var ps: typeof _.ps
var syncProcessCwd: typeof _.syncProcessCwd
var updateArgv: typeof _.updateArgv
```

fix(global): add missing types

---

src/core.ts
src/goods.ts
src/util.ts

refactor: simplify setup checks

---

quotes.md

docs: mention qoute for pwsh

---

package.json

Fixes #<number_goes_here>
```js
```

Release 8.1.3

---

package-lock.json
package.json

Align internal dep tree versions, optimize final bundle size

perf: update @webpod/ps to v0.0.0-beta.7

---

man/zx.1
package-lock.json
package.json

* Mention `cwd` option in man help
* Bump the pkg version to 8.1.5

docs: mention `cwd` option in man

---

test/vendor.test.js

test(unit): check YAML extras presence

---

src/core.ts
src/goods.ts
src/util.ts
test/core.test.js
test/util.test.js

```js
$.preferLocal = '/some/to/bin'
$.preferLocal = ['/path/to/bin', '/another/path/bin']
```

feat: let `$.preferLocal` accept dir

---

.github/workflows/test.yml
package-lock.json
package.json

Enhance test flow:
* cron 0 12 */4 * *
* add ts@rc
* add nodejs 22-nightly

test: add nodejs nightly and ts rc to the test matrix

---

package-lock.json
package.json

fix: enhance abort handlers clean up

---

api.md

docs(api): add chainable presets example

---

test/core.test.js

test: extend presets test case

---

package.json
src/core.ts
test/core.test.js

fix: propagate rejection on pipe

---

src/core.ts
src/util.ts
src/vendor-core.ts
test/core.test.js
test/util.test.js

fix: detect Duplex on pipe

---

.size-limit.json
package-lock.json
package.json
src/core.ts
src/util.ts
test-d/core.test-d.ts

Inherits [zurk's lazyloads](https://github.com/webpod/zurk/blob/main/src/main/ts/spawn.ts#L227)

perf: optimize `ProsessOutput` mem consumption

---

src/cli.ts

perf: strengthen code block patterns

---

package-lock.json
package.json
scripts/build-dts.mjs
src/core.ts
src/util.ts
src/vendor-core.ts

perf: shrink a few bytes

---

src/core.ts
test/cli.test.js

test: improve proc hand detection

---

package-lock.json
package.json
test/core.test.js

fix: fill stdall store on sync spawn

---

src/core.ts
src/deps.ts

Just clarifies the `ProcessPromise` methods hierarchy

style: group `ProcessPromise` methods

---

.github/workflows/test.yml
package.json

ci: add node `--strip-types` smoke test

---

package-lock.json
package.json
src/core.ts
test/core.test.js

refactor: simplify `promisifyStream` helper

---

package-lock.json
package.json
src/core.ts

chore: minor code imprs

---

src/goods.ts
test/cli.test.js
test/core.test.js
test/deps.test.js
test/fixtures/interactive.mjs
test/fixtures/require.mjs
test/fixtures/ts-project/script.ts
test/global.test.js
test/goods.test.js

style: use let for dynamic values only

---

test/core.test.js
test/smoke/bun.test.js

test: stdio inherit

---

test/core.test.js

test: mixed stdio opts handling

---

test/core.test.js

test: check values on pipe reject propagations

---

package-lock.json
package.json
scripts/build-js.mjs

build: use reexport to bind esm and cjs bundles

---

src/core.ts
test/smoke/bun.test.js
test/smoke/node.test.mjs

Root cause: https://github.com/oven-sh/bun/issues/6393#issuecomment-1783547154

test(smoke): check ctx isolation

---

scripts/generate-vendor-tests.mjs

test: assert 3rd party reexports

---

package-lock.json
package.json
scripts/build-jsr.mjs
test/it/build-jsr.test.js

continues #989 #980 
fyi, @easymikey

test: optimize jsr artifact test

---

src/core.ts
test/core.test.js

refactor: minor code improvements

---

.github/workflows/dev-publish.yml
package-lock.json
package.json

ci: apply pkg-clean to dev publish

---

.size-limit.json
man/zx.1
src/cli.ts
src/core.ts
src/goods.ts
src/util.ts
test/goods.test.js
test/index.test.js
test/util.test.js

```bash
zx --prefer-local ./script
```

feat(cli): provide `--prefer-local` option

---

.size-limit.json
src/core.ts
src/goods.ts
src/util.ts
test/cli.test.js
test/util.test.js

test: add `transformMarkdown` test

---

src/goods.ts

fix: suppress spinner in quiet mode

---

docs/cli.md
src/util.ts
test/util.test.js

fix: parseDotenv tweak ups

---

src/util.ts

chore: fix quote regexp

---

docs/markdown-scripts.md
src/cli.ts
src/deps.ts

feat(cli): allow ts be extracted from markdown

---

.github/workflows/test.yml

ci: explicitly declare permissions for test.yml

---

docs/process-promise.md

docs: mention `halt` and `run` API

---

src/deps.ts
src/util.ts

chore: simplify regexes

---

src/deps.ts

fix: add `diagnostics_channel` to built-ins list

---

src/core.ts
src/util.ts
test/core.test.js

feat: add `id` to log entries

---

.size-limit.json
src/core.ts
src/util.ts
test/core.test.js

feat:  introduce `end` event for logger

---

package-lock.json
package.json

chore: bump pkg version to 8.3.1

---

scripts/deno.polyfill.js
test/cli.test.js

chore(deno): minor polyfill refactoring

---

src/cli.ts
src/repl.ts

fix(cli): file protocol check

---

src/repl.ts

feat: handle `ZX_REPL_HISTORY` envvar

---

src/cli.ts
src/core.ts
test/cli.test.js

refactor(cli): optimize md parser

---

src/goods.ts
src/repl.ts

style: use `trimEnd()` instead of regexp replace

---

.github/workflows/dev-publish.yml
.github/workflows/npm-publish.yml
.github/workflows/test.yml
.size-limit.json
package-lock.json
package.json
src/cli.ts

chore: update yaml to v2.7.0

---

.size-limit.json
package-lock.json
package.json
src/cli.ts
src/core.ts
src/deps.ts
src/util.ts
src/vendor-core.ts
test/bench/buf-join.mjs

refactor: avoid redundant buffer to string

---

src/core.ts
test/bench/buf-join.mjs

fix: timeout signal override

---

.github/workflows/test.yml
src/cli.ts
src/core.ts
src/error.ts
src/index.ts
test/it/build-jsr.test.js

test: enable jsr and integration test suites

---

src/core.ts
test-d/core.test-d.ts

refactor: simplify `ProcessOutput` constructor

---

src/core.ts
test/core.test.js

refactor: simplify `ProcessOutput` internals

---

src/core.ts

refactor: enhance `nothrow` option

---

docs/api.md
docs/process-promise.md
test/core.test.js

docs: describe `nothrow` option

---

package-lock.json
package.json

chore: bump to v8.4.0

---

docs/setup.md

docs: mention `@types/node` and `@types/fs-extra` requirements

---

docs/typescript.md

docs: update TS usage example, mention `--experimental-strip-types` flag

---

src/cli.ts

fix(cli): disable `ZX_EVAL` handling

---

package-lock.json
package.json
scripts/prepublish-lite.mjs

chore: bump version to 8.4.2

---

.github/workflows/dev-publish.yml

build: update docker actions

---

.github/workflows/dev-publish.yml
dcr/Dockerfile
docs/setup.md
package.json

ci: build improvements

---

package-lock.json

chore: up dev deps, apply npm audit fix

---

build/3rd-party-licenses
build/vendor-core.cjs
build/vendor-core.d.ts
package-lock.json
package.json

chore: update zurk to v0.10.3

---

package-lock.json
package.json

chore: bump version to v8.5.0

---

scripts/build-jsr.mjs

chore: fix JSR pkg scope

---

scripts/build-jsr.mjs

relates https://github.com/google/zx/actions/runs/14178982863/job/39720546542#step:10:27

build(jsr): link yaml

---

scripts/build-jsr.mjs

relates https://github.com/google/zx/actions/runs/14179286919/job/39721500697#step:10:104

build(jsr): refactor imports map

---

scripts/build-jsr.mjs

chore: update build-jsr.mjs

---

.size-limit.json
build/index.cjs
scripts/build-jsr.mjs
src/index.ts

build(jsr): exclude cli.ts

---

.github/workflows/dev-publish.yml
.github/workflows/npm-publish.yml

ci: enable additional publish flows

---

docs/setup.md

docs: update setup guide

---

.size-limit.json
build/3rd-party-licenses
build/vendor-extra.cjs
package-lock.json
package.json

perf: update deps

---

docs/getting-started.md
docs/setup.md

docs: mention docker in setup guide

---

.size-limit.json
README.md
docs/cli.md
docs/setup.md
docs/typescript.md

docs: mention `node --import` and impr CLI description

---

package.json

build: flush bundles dir before build

---

build/cli.cjs
build/core.cjs
build/core.d.ts
build/goods.cjs
build/index.cjs
build/log.d.ts
build/md.d.ts
build/util.cjs
build/util.d.ts
build/vendor-core.cjs
build/vendor-core.d.ts
build/vendor-extra.cjs
package.json
scripts/build-js.mjs
scripts/build-jsr.mjs
src/cli.ts
src/globals-jsr.ts
tsconfig.json

fix: workaround jsr global types

---

package-lock.json
package.json

chore: bump v to 8.5.2

---

scripts/build-jsr.mjs

chore(jsr): attach jsr.json to `include`

---

.github/workflows/test.yml
docs/setup.md

test: add graaljs smoke test

---

build/index.cjs
build/util.cjs
docs/cli.md
docs/markdown.md
src/goods.ts
src/util.ts
test/util.test.js

chore: minor goods imprs, md usage update

---

.github/workflows/test.yml

ci: add nodejs 24 to test matrix

---

.size-limit.json
build/cli.cjs
build/core.cjs
build/deps.cjs
build/deps.d.ts
src/cli.ts
src/core.ts
src/deps.ts
test/deps.test.js

refactor: decompose `installDeps`

---

.size-limit.json
build/core.cjs
build/vendor.cjs
build/vendor.d.ts
src/log.ts
src/vendor.ts

chore: shrink a few bytes

---

docs/.vitepress/config.mts
docs/lite.md
docs/process-promise.md
docs/setup.md

docs: provide zx@lite description

---

dcr/Dockerfile
docs/setup.md
test/it/build-dcr.test.js

chore: update docker base image to node:24-alpine

---

.commitlintrc
.github/workflows/test.yml
.size-limit.json
README.md
docs/setup.md
lefthook.yml
package-lock.json
package.json

* Docs improvements
* Adds commitlint hooks

docs: describe platform compatibility

---

.size-limit.json
README.md
docs/shell.md

docs: improve `bash` description

---

package-lock.json
package.json

chore: bump version to v8.6.1

---

.github/workflows/dev-publish.yml
.github/workflows/docs.yml
.github/workflows/osv.yml
.github/workflows/publish.yml
.github/workflows/zizmor.yml

ci: update github actions

---

docs/api.md

docs: add fetch timeout example

---

README.md

docs: fix readme svg size

---

examples/fetch-weather.mjs

Helps fix #981
```bash
cd examples
./fetch-weather.mjs London
zx ./fetch-weather.mjs "New York"
```
Output of example:
I am unsure whether I need to do tests, as this is a feature example to showcase `zx`, but not a feature for `zx` itself. Please let me know if I should do that. 
Also, please let me know if you would like more examples than just the one I provided. This is a really neat project and I'm happy to provide more.

Introduce weather fetch example

---

.size-limit.json
build/core.cjs
src/core.ts
test/core.test.js

fix: check if `ProcessPromise` is settled on kill and abort

---

docs/process-promise.md
package-lock.json
package.json
test/smoke/win32.test.js

chore: bump version to v8.7.0, minor docs imprs

---

.size-limit.json
build/3rd-party-licenses
build/vendor-core.cjs
package-lock.json
package.json

fix: update @webpod/ps to v0.1.4 to handle eperm issues

---

.size-limit.json
build/core.cjs
build/util.cjs
src/core.ts
src/util.ts
test/util.test.js

refactor: rm redundant internal vars

---

docs/.vitepress/config.mts
docs/api.md
docs/architecture.md
docs/contribution.md

docs: add architecture notes

---

package-lock.json
package.json

chore: bump version to v8.8.0

---

test/smoke/node.test.mjs

test: check `fetch()` polyfill for legacy nodejs versions

---

build/deps.cjs
src/deps.ts

fix(cli): filter `npm install` flags

---

build/core.cjs
build/core.d.ts
build/util.d.ts
build/vendor-core.d.ts
src/core.ts
src/util.ts
src/vendor-core.ts
test/core.test.js

feat: accept array as  `stdio()` arg

---

.size-limit.json
build/core.cjs
build/core.d.ts
build/log.d.ts
src/core.ts
src/log.ts
test/log.test.ts

feat: log kill event

---

.size-limit.json
build/core.cjs
build/core.d.ts
src/core.ts

refactor: optimize shell setters

---

.github/workflows/dev-publish.yml
.github/workflows/publish.yml
package-lock.json
package.json

chore: bump v to 8.8.1

---

scripts/build-pkgjson-lite.mjs
scripts/build-pkgjson-main.mjs

ci: minor manifest gen improvements

---

.github/workflows/test.yml
package-lock.json
package.json

chore: update @types/node to v24.3.0

---

.github/workflows/codeql.yml
.github/workflows/dev-publish.yml
.github/workflows/docs.yml
.github/workflows/jsr-publish.yml
.github/workflows/publish.yml
.github/workflows/test.yml
.github/workflows/zizmor.yml

ci: update actions to `checkout@v5`, `download-artifact@v5`
