- index.d.ts
- package.json
This PR fixes type definitions by:
1. Including them in the package.
2. Adding missing `$.prefix` and `$.quote`.
> Fix TypeScript definitions

- index.mjs
Fixes #36
Custom promisify fixes the issue with readline breaking in node <= v15.7.0
This might be happening because readline's question function has a callback function. And instead of returning error in the first argument it has the answer itself ?
> custom promisify implementation for readline

- README.md
- index.d.ts
- index.mjs
Improve readability when a query is not needed. From usage in https://github.com/google/zx/issues/61#issuecomment-839551685.
> Don't require the argument `query` for `question()`

- index.mjs
ProcessOutput is returned even though the stdio of the child process is not finished.
``` javascript
#!/usr/bin/env zx
for(let i=0; i<5; i++) {
$`date`.then(r => console.log(i, r.toString()))
}
```
result
```
./main.mjs  
$ date
$ date
$ date
$ date
$ date
2021년 5월 16일 일요일 17시 16분 46초 KST
2021년 5월 16일 일요일 17시 16분 46초 KST
2021년 5월 16일 일요일 17시 16분 46초 KST
0 2021년 5월 16일 일요일 17시 16분 46초 KST
1 2021년 5월 16일 일요일 17시 16분 46초 KST
2 2021년 5월 16일 일요일 17시 16분 46초 KST
3 
4 
2021년 5월 16일 일요일 17시 16분 46초 KST
2021년 5월 16일 일요일 17시 16분 46초 KST
```
somtimes
```
./main.mjs 
$ date
$ date
$ date
$ date
$ date
2021년 5월 16일 일요일 17시 55분 13초 KST
2021년 5월 16일 일요일 17시 55분 13초 KST
2021년 5월 16일 일요일 17시 55분 13초 KST
2021년 5월 16일 일요일 17시 55분 13초 KST
0 2021년 5월 16일 일요일 17시 55분 13초 KST
1 2021년 5월 16일 일요일 17시 55분 13초 KST …
```
> Fix when child stdio is over

- zx.mjs
https://omrilotan.medium.com/npx-breaking-on-ci-b9f3f61d4676
relates https://github.com/google/zx/commit/0cf9b9dc92c28f59f25e3db81c62846c37bcef82
> fix: make internal npx invocation compatible with npm v6

- README.md
- index.d.ts
- index.mjs
> feat: add `fs.constants` field to global `fs`, add missed `fs` export

- .gitignore
- index.d.ts
Global injects should be declared as vars so that they can be overridden if needed. 
Like here: https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L19303)
> fix(types): declare global injects as vars

- README.md
- index.d.ts
- index.mjs
- package.json
- test.mjs
Fixes #175
`globby` bases on mentioned `fast-glob` and add some more features. I didn't find any other proper popular alternatives.
> Add `globby`

- test.mjs
- zx.mjs
Continuing the discussion  from #28, this PR includes:
- A test that runs a script from the PATH environmental variable.
- A change in the default case of parsing the first argument to use `filepath = resolve(firstArg)` instead of `filepath = join(process.cwd(), firstArg)` because this allows to run a script from PATH on Windows with Git bash. zx was able to run a script from PATH on Linux, even before this change, because it didn't use the default case (I think).
The problem, though, is that GitHub actions tests on Ubuntu so the test does not confirm that it works on Windows. If Windows support is important, we can configure, in the future, another job that runs the tests on Windows (?)—and change some of them because they fail on Windows.
> Run script from path

- test.mjs
- zx.mjs
Currently, when a CLI option is passed, you just get the usage instructions back:
```
yarn zx --quiet myscript.ts
usage: zx [--quiet] [--shell=<path>]
[--prefix=<command>]
<script>
```
> Fix CLI options such as --quiet

- index.mjs
The code `new Error().stack.split('at ')` in `cd()` gives an incorrect output when `cd` is called from a function whose name ends with "at". For example:
```js
function cat() {
cd("cc");
}
function f() {
cat();
}
f();
/*
$ cd cc
cd: cc: No such directory
at c
*/
```
> Fix split regex for stack.split()

- index.mjs
- test.mjs
Fixes #191 
This PR refactors ProcessPromise. 
Now call $ does not create the child process. then() creates child process.
> Use inherited stdin instead of piped

- README.md
- package.json
Fixes #214 
It turns out I noted the Node version requirement incorrectly. As you pointed out [here](https://github.com/sindresorhus/globby/blob/6e099869e77240f705a951b6a80c09d3bab55423/package.json#L16), it's 14.13.1, not 14.13.0.
Sorry! 😅
> Update Node version requirement (correctly).

- README.md
- index.d.ts
- index.mjs
- package-lock.json
- package.json
- test.mjs
> feat: add yaml dependency

- package-lock.json
- package.json
Remove types for node-fetch because the package is deprecated. https://www.npmjs.com/package/@types/node-fetch. The 3.0.3 version from the lock file is empty when you install it.
> Remove @types/node-fetch

- README.md
Checked the link, skipping the redirect HTTP => HTTPS this way 0:-)
~~Fixes #<issue_number_goes_here>~~
#269 was unexpectedly closed, so here is another try :)
> README.md: HTTP => HTTPS, second try

- README.md
- index.d.ts
- index.mjs
* Mocking and testing: ESM mocking is not handy, so if we'd like to override `cp.spawn` we have to create a new VM context with clean module cache, read files, parse them to build proper virtual refs, evaluate, etc, etc. Let's just don't.
* Debug and audit. For example, we can easily wrap the default impl and capture all internal cmd invocations of script to some file.
> feat: provide configurable `spawn`

- README.md
- experimental.d.ts
- experimental.mjs
- test.mjs
Some cmds (like `npm whoami`) may hit the throttling limit, so a `delay` between call attempt might be very useful.
> feat: add optional delay for `retry`

- README.md
- index.d.ts
- index.mjs
- test.mjs
**Maintainer**: 200 Mb is enough for stdout. No one will use `zx` to test ELK, spark and kuber orchestration.
**QIWI**: Hold my beer )
> feat: configurable `maxBuffer` spawn option

- package.json
- test.mjs
- zx.mjs
The common case is to assert the util version before running. So let's print zx version as semver-compatible string (`x.x.x` or `vx.x.x`) like the most js utils do.
```
node --version
v16.14.0 // ok
npm -v
8.5.4 // ok
git --version
git version 2.35.1 // not ok
```
> feat: print zx version in semver-compatible format

- .gitignore
- README.md
- src/index.mjs
- zx.mjs
> feat: load experimental assets as globals via `--experimental` flag

- src/index.mjs
- test.mjs
`cwd` should not mutate inside $ call.
> fix: bind cwd to spawn call

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- package.json
- src/globals.d.ts
- src/index.d.ts
- src/index.mjs
- test.mjs
> feat: export `which` package as global

- README.md
- src/experimental.d.ts
- src/experimental.mjs
- src/index.d.ts
- test.mjs
> feat: introduce experimental `withTimeout` helper

- src/experimental.mjs
- test.mjs
- zx.mjs
util `stringify` has its own `instanceof ProcessOutput` check, so it can be removed from `echo`
> refactor: simplify echo helper, add tests for experimental features

- src/experimental.mjs
```
npm % node src/main/js/index.mjs --lockfile=../../yarn.lock --temp=../../tempy
file:///Users/antongolub/projects/sros/node_modules/zx/src/experimental.mjs:24
if (delay) await sleep(delay)
^
ReferenceError: sleep is not defined
```
> fix: do not rely on globals inside `experimental.mjs`

- .github/workflows/npm-publish.yml
- .github/workflows/test.yml
- package.json
- test/experimental.test.mjs
- test/full.test.mjs
- test/index.test.mjs
- test/test-utils.mjs
- test/zx.test.mjs
Refactor test-utils:
* Introduce `test`, `test.only` and  `test.skip` helpers
* Highlight failed tasks in red
* Apply CLI filter argument to test file paths
* Add test exec timeout
> test: tweak up test-utils

- README.md
- package.json
- zx.mjs
```js
// index.js
import {$} from 'zx'
$.extra = extra
$.prefix = prefix
// cli.js
#!/usr/bin/env node
import './index.js'
import 'zx/cli'
```
> feat: add zx.mjs to pkg exports

- src/index.d.ts
index.mjs does `import which from "which"`, not `import * as which from "which"`; this causes problems when you are in TypeScrip's module mode because it automatically disables the interop setting which makes calling a `*` imported module as a function legal.
> Make `which` a default import in index.d.ts

- README.md
- package.json
- src/cli.ts
- src/context.ts
- src/core.ts
- src/experimental.ts
- src/print.ts
- src/util.ts
- test/cli.test.js
- test/experimental.test.js
- test/log.test.js
> feat: provide customizable logger

- package.json
- src/context.ts
- src/core.ts
- src/goods.ts
- test/index.test.js
> fix getCtx()

- src/core.ts
- test/index.test.js
> Fix promise ctx

- src/context.ts
- src/core.ts
- test/experimental.test.js
> fix: rm redundant root ctx assignment

- src/cli.ts
zx-extra/index.js
```js
$.verbose = false
```
zx-extra/cli.js
```js
#!/usr/bin/env node
import './index.mjs'
import 'zx/cli'
$.verbose // true
```
> fix: avoid redundant `$.verbose` reassignment on CLI init

- README.md
I struggled with switching Node.js version via [nvm](https://github.com/nvm-sh/nvm) in my `zx` script because docs are misleading currently - `nvm use 16` must be part of prefix to allow using Node.js 16 inside the context
I found fix was provided in #362 but docs are incorrect
---
```js
await $`node --version`
let version = await within(async () => {
$.prefix += 'export NVM_DIR=$HOME/.nvm; source $NVM_DIR/nvm.sh;'
await $`nvm use 16`
return $`node --version`
})
echo(version);
```
```
$ node --version
v20.2.0
$ nvm use 16 <--- switching to version 16
Now using node v16.20.0 (npm v8.19.4)
$ node --version
v20.2.0 <---- but still 20 is used
v20.2.0
```
```js
await $`node --version`
let version = await within(async () => {
$.prefix += 'export NVM_DIR=$HOME/.nvm; source $NVM_DIR/nvm.sh; nvm …
```
> docs: fix example for within function

- README.md
- src/core.ts
- test/core.test.js
> Enhance cd to accept ProcessOutput

- package-lock.json
- package.json
- scripts/build-dts.mjs
- src/core.ts
- src/index.ts
- src/vendor.ts
- test/core.test.js
- test/win32.test.js
Closes #600 
* Mostly separates `zx/core` as mentioned in #589 
* Provides $ init / preset API
```ts
const $$ = $({ nothrow: true, quiet: true })
await $$`exit 1`
```
> refactor: separate core

- package-lock.json
- package.json
- src/core.ts
- test/core.test.js
closes #527
```ts
const p1 = $`sleep 9999`
setTimeout(() => p.abort(), 100)
const ac = new AbortController()
const p2 = $({ ac })`sleep 9999`
setTimeout(() => ac.abort(), 100)
```
> feat: introduce `abort()` method

- package-lock.json
- package.json
- src/core.ts
- test/core.test.js
Closes #720
```ts
const p1 = $({ input: 'foo' })`cat`
const p2 = $({ input: Readable.from('bar') })`cat`
const p3 = $({ input: Buffer.from('baz') })`cat`
const p4 = $({ input: p3 })`cat`
const p5 = $({ input: await p3 })`cat`
```
> feat: provide `input` option

- src/core.ts
- test/core.test.js
closes #690
```ts
test('ProcessPromise: implements toString()', async () => {
const p = $`echo foo`
assert.equal((await p).toString(), 'foo\n')
})
test('ProcessPromise: implements valueOf()', async () => {
const p = $`echo foo`
assert.equal((await p).valueOf(), 'foo')
assert.ok((await p) == 'foo')
})
```
> feat: add `ProcessPromise.valueOf()`

- src/core.ts
- test/core.test.js
closes #681
```ts
const o1 = $.sync`echo foo`
const o2 = $({ sync: true })`echo foo`
o1.stdout //  'foo\n'
o2.stdout //  'foo\n'
```
> feat: provide sync API

- package-lock.json
- package.json
- scripts/build-dts.mjs
- src/deps.ts
- src/vendor.ts
- test/deps.test.js
- test/fixtures/js-project/package-lock.json
```ts
// This should be captured
import 'foo' // @1.2.3
// But the rest should be ignored
// import bar from 'bar'
/* import baz from 'baz' */
```
> refactor: use depseek for deps extraction

- .github/workflows/test.yml
- src/core.ts
- src/util.ts
- test/bun.test.js
- test/cli.test.js
- test/util.test.js
- test/win32.test.js
> refactor: enhance stack from

- src/cli.ts
- src/core.ts
- test/cli.test.js
> feat: add `$.postfix option

- src/core.ts
- src/globals.ts
- test/core.test.js
- test/win32.test.js
> refactor: disable default powershell setup

- src/core.ts
- src/globals.ts
- src/util.ts
- test/core.test.js
- test/index.test.js
- test/package.test.js
- test/smoke/win32.test.js
```ts
process.cwd() // foo
$.cwdHook = false
within(async() => {
cd('/bar')
await sleep(10)
await $`pwd` // now it is `/qux`, not `/bar`
})
cd('/qux')
```
> feat: let `cwdHook` be configurable

- package-lock.json
- package.json
- src/core.ts
- test/core.test.js
- test/fixtures/js-project/package-lock.json
relates #753
Needs additional research.
> fix: disable multiline feature

- package-lock.json
- package.json
- src/core.ts
- test/core.test.js
- test/fixtures/js-project/package-lock.json
closes #768
relates #734
```ts
const ac = new AbortController()
const signal = ac.signal
const p = $({ signal })`sleep 9999`
setTimeout(() => ac.abort(), 100)
```
> feat: support `signal` opt

- .gitattributes
- src/cli.ts
- test/cli.test.js
- test/fixtures/markdown-crlf.md
Fixes #787
support Windows CRLF line ending when split lines in transformMarkdown.
> #787 support CRLF for markdown script

- src/core.ts
- src/globals.ts
- test/core.test.js
- test/index.test.js
- test/smoke/win32.test.js
Fixes https://github.com/google/zx/issues/785
No documentation was added. I haven't found any documentation for other helpers apart from release notes...
A smoke test was added to `win32` test but I'm not sure if it's a good idea.
- `pwsh` is not available by default
- `pwsh` can be used on any supported platform
So the last commit can be dropped. Or I can create a new smoke test.
A new helper `usePwsh` to use `pwsh` shell (PowerShell v7+).
```js
import { usePowerShell, usePwsh } from 'zx'
usePowerShell() // to enable powershell.exe (PowerShell v5 on Windows)
usePwsh()       // switch to pwsh (PowerShell v7 on any supported platform)
```
Tested on Windows 11 and Fedora 38
<table>
<tr><td>
```js
usePwsh()
console.log((await $`echo 'Foo' && echo 'Bar'`).stdout)
```
</td><td>
```
Foo
Bar
``` …
> feat: add `usePwsh` helper for PowerShell v7+

- .vitepress/config.mts
- api.md
- cli.md
- configuration.md
- contribution.md
- getting-started.md
- migration-from-v7.md
- package-lock.json
- package.json
- package.md
- process-output.md
- process-promise.md
- setup.md
- typescript.md
> Docs for v8.0.0

- src/core.ts
- src/util.ts
- test/util.test.js
> feat: add a newline after commands that don't end their output with one

- package.json
According to Node.js documentation the types should always be listed first when using package exports, see:
https://nodejs.org/api/packages.html#community-conditions-definitions
This also fixes an issue with `eslint-plugin-import` throwing a warning `Parse errors in imported module 'zx': parserPath or languageOptions.parser is required! (undefined:undefined)` due to the wrong order of package exports.
> fix: list types first in package exports

- src/cli.ts
before:
```js
if (argv.quiet) $.verbose = false
```
after:
```js
if (argv.quiet) $.quiet = true
```
> fix: bound `--quiet` flag with `$.quiet`

- src/core.ts
- test/core.test.js
continues #811
relates #764
```js
const p = $`echo 'foo\nbar'`
await p.text()        // foo\n\bar\n
await p.text('hex')   //  666f6f0a0861720a
await p.buffer()      //  Buffer.from('foo\n\bar\n')
await p.lines()       // ['foo', 'bar']
await $`echo '{"foo": "bar"}'`.json() // {foo: 'bar'}
```
> feat: provide format methods for `ProcessPromise`

- src/core.ts
- test/core.test.js
```js
const p = $`sleep 999`
const {signal} = p
const res = fetch('https://example.com', {signal})
p.abort('reason')
```
> feat: expose signal prop from ProcessPromise

- configuration.md
- process-promise.md
> docs: describe `$.preferLocal`, `abort()`API and `ProcessPromise` formatters

- src/core.ts
- test/core.test.js
relates #710
```js
const p = $`echo foo`
p.quiet()        // enable silent mode
p.quiet(false)   // then disable
p.verbose()      // enable verbose/debug mode
p.verbose(false) // and turn it off
await p
```
> feat: add ProcessPromise `.verbose()` for symmetry with`.quiet()`

- src/cli.ts
- test/cli.test.js
Set exit code 1 on incorrect (empty) parametrization.
```bash
zx --foo || echo test
```
↓
```
zx 8.1.1
A tool for writing better scripts
...
test
```
> fix(cli): return exit code 1 on incorrect inputs

- package.json
> fix: set cjs bundle as legacy `main` entrypoint

- src/core.ts
- src/util.ts
- test/util.test.js
```js
// Ensures EOL
if (stderr && !stderr.endsWith('\n')) c.on.stderr?.(eol, c)
if (stdout && !stdout.endsWith('\n')) c.on.stdout?.(eol, c)
```
> fix: apply EOL ensurer to the last chunk only

- src/core.ts
```js
$.log({kind: 'custom', data: 'foo'})
```
> fix: capture `custom` log event

- package-lock.json
- package.json
- src/vendor.ts
> perf: remove node abort controller in favor of built-in node-fetch polyfill

- scripts/build-js.mjs
https://github.com/unjs/node-fetch-native/blob/main/src/node.ts#L24
https://github.com/unjs/node-fetch-native/pull/128
> fix: disable redundant node-fetch-native runtime check (deno)

- package-lock.json
- package.json
- src/core.ts
- src/vendor.ts
- test/core.test.js
closes #650 
relates #675
```js
const getFixedSizeArray = (size) => {
const arr = []
return new Proxy(arr, {
get: (target, prop) =>
prop === 'push' && arr.length >= size
? () => {}
: target[prop],
})
}
const store = {
stdout: getFixedSizeArray(1),
stderr: getFixedSizeArray(1),
stdall: getFixedSizeArray(0),
}
const p = await $({ store })`echo foo`
p.stdout.trim() //  'foo'
p.toString()    // ''
```
> feat: provide `store` opt

- src/cli.ts
```js
${chalk.bold('Options')}
--quiet              suppress any outputs
--verbose            enable verbose mode
```
> docs: mention CLI `verbose flag

- src/globals.ts
In my company's repo, we needed to change the defaults object to set the global configuration (I don't know why but I had to), and I found that when I use `import "zx/globals"`, it will mount `defaults` obj to globalThis, but there is no type definition in mjs file, so I want to fix it.
```js
var defaults: typeof _.defaults
```
> fix(global): add missing types

- .size-limit.json
- package-lock.json
- package.json
- scripts/build-js.mjs
- src/vendor-extra.ts
- test/vendor.test.js
* Remove redundant (undocumented) YAML API extras
* Override yaml pkg entry point from cjs to esm: reduce vendor bundle size by ~65Kb
Fixes #863
> fix: omit redundant yaml API extras

- src/core.ts
- test/core.test.js
> test(core): enhance cwd related test for `within`

- package-lock.json
- package.json
- src/core.ts
- test/core.test.js
Fixes #881 
```js
const $$ = $({ nothrow: true })
assert.equal((await $$`exit 1`).exitCode, 1)
const $$$ = $$({ sync: true }) // Both {nothrow: true, sync: true} are applied
assert.equal($$$`exit 2`.exitCode, 2)
```
> feat: let $ presets be composable

- src/util.ts
- test/util.test.js
```js
assert.throws(() => parseDuration('f2ms'))
assert.throws(() => parseDuration('2mss'))
```
> fix: enhance duration parser

- .size-limit.json
- src/core.ts
- src/util.ts
- src/vendor-core.ts
- test/core.test.js
Enables [zurk-like](https://github.com/webpod/zurk/blob/main/src/test/ts/x.test.ts#L143) pipe literals:
```js
const p = await $`echo foo`.pipe`cat`
assert.equal(p.stdout.trim(), 'foo')
```
> feat: enable stringLiterals for `pipe()` API

- .size-limit.json
- man/zx.1
- src/cli.ts
- test/cli.test.js
closes #929
```js
NODE_OPTIONS='--experimental-strip-types' npx zx --ext='.ts' <<< 'const foo:string="bar"; console.log(foo)'
```
> feat(cli): allow overriding default script extension

- package-lock.json
- package.json
> chore: bump pkg version to v8.2.1

- package-lock.json
- package.json
- test/core.test.js
> fix: handle nullable stdout/stderr

- .size-limit.json
- src/core.ts
- test/core.test.js
continues #949
This part enables:
```ts
const { stdout } = await $({ halt: true })`echo "hello"`
.pipe`awk '{print $1" world"}'`
.pipe`tr '[a-z]' '[A-Z]'`
.run()
```
> fix: autorun halted processes on pipe run

- .size-limit.json
- src/core.ts
- src/util.ts
- test/core.test.js
continues #949
```ts
const getUpperCaseTransform = () =>
new Transform({
transform(chunk, encoding, callback) {
callback(null, String(chunk).toUpperCase())
},
})
// $ > stream (promisified) > $ 
const o1 = await $`echo "hello"`
.pipe(getUpperCaseTransform())
.pipe($`cat`)
o1.stdout //  'HELLO\n'
// stream > $
const file = tempfile()
await fs.writeFile(file, 'test')
const o2 = await fs
.createReadStream(file)
.pipe(getUpperCaseTransform())
.pipe($`cat`)
o2.stdout //  'TEST'
```
> feat: let $ be piped from stream

- src/core.ts
- src/util.ts
- test-d/core.test-d.ts
- test/core.test.js
continues #949
Promisified pipe result exposes the closest left `ProcessOutput` data for backward compatibility
```ts
const file = tempfile()
const fileStream = fs.createWriteStream(file)
const p = $`echo "hello"`
.pipe(getUpperCaseTransform())
.pipe(fileStream)
const o = await p
assert.ok(p instanceof WriteStream)
assert.ok(o instanceof WriteStream)
assert.equal(o.stdout, 'hello\n')
assert.equal(o.exitCode, 0)
assert.equal((await fs.readFile(file)).toString(), 'HELLO\n')
```
> fix: mixin `ProcessOutput` data to promisified pipe value

- .size-limit.json
- src/core.ts
- test/core.test.js
> Add async generator logic to ProcessPromise

- package-lock.json
- package.json
- src/core.ts
- test/cli.test.js
- test/core.test.js
> feat: inherit abort signal on piping

- man/zx.1
- src/cli.ts
- src/deps.ts
- test/deps.test.js
Add custom npm registry with composition install and registry flags.
Fixes #972
```js
zx --install --registry='https://npm-proxy.example.com' script.mjs
```
> feat: add custom npm registry when installing dependencies

- docs/process-promise.md
- src/core.ts
- test/core.test.js
Now, instead of
```js
await $`echo "Hello, stdout!"`
.pipe(fs.createWriteStream('/tmp/output.txt'))
```
you can simply do
```js
await $`echo "Hello, stdout!"`
.pipe('/tmp/output.txt')
```
Fixes #976
> feat: direct piping to file shortcut

- src/core.ts
- test/core.test.js
Test for error case for iterator
> test: add test for error case of iterator

- scripts/build-tests.mjs
- src/goods.ts
- test/goods.test.js
- test/vendor-export.test.js
closes #1008
```ts
export async function spinner<T>(
title: string | (() => T),
callback?: () => T
): Promise<T> {
if (typeof title == 'function') {
callback = title
title = ''
}
if (process.env.CI) return callback!()
```
> fix: disable spinner in CI

- .size-limit.json
- src/core.ts
- test/core.test.js
Closes #978 
```js
const p = $`echo foo >&2; echo bar`
const o1 = (await p.pipe.stderr`cat`).toString()
const o2 = (await p.pipe.stdout`cat`).toString()
assert.equal(o1, 'foo\n')
assert.equal(o2, 'bar\n')
```
> feat: enable stream picking on `pipe()`

- src/core.ts
> fix: let `shell` path be preconfigured via env

- docs/cli.md
- docs/process-promise.md
> docs: sync docs with impl

- .size-limit.json
- src/core.ts
- test/core.test.js
relates #1028
```js
const foo = '#bar'
const baz = 1
const p = $`echo ${foo} --t ${baz}`
p.cmd       // "echo $'#bar' --t 1")
p.fullCmd   // "set -euo pipefail;echo $'#bar' --t 1"
```
> feat: expose ProcessPromise `fullCmd` and unique `id`

- src/cli.ts
A bit more consistency with nodejs
https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs
```bash
zx --env-file='.env' script.mjs
```
> feat(cli): alias `env-file` and `env` options

- src/cli.ts
- src/util.ts
> refactor: simplify quote regexp

- src/cli.ts
What's wrong now:
* Processing `readme.md` may override existing user's local `readme.md.mjs`
* Markdown flow ignores `--ext` and applies `.mjs` everytime, so cjs contents fails.
* Fetching from https ignores `--ext` option too: `https://example.com/path/script.js.bak` calls `<temp>script.js.bak` instead of `<temp>script.js.mjs`
> fix(cli): always check if tempfile exists

- docs/v7/api.md
- src/goods.ts
- test/cli.test.js
- test/core.test.js
- test/export.test.js
- test/goods.test.js
- test/util.test.js
Fixes #975
```js
/// './path/prod.env'
FOO=BAR
---
/// index.js
$.env = './path/prod.env'
await $`echo $FOO`.stdout // BAR
```
> feat: provide support for .env files injects via API

- .size-limit.json
- docs/api.md
- src/core.ts
* fix: ignore `timeout` setting for sync or resolved processes
* fix: invoke `setTimeout` if process is running
> fix(core): handle `timeout` setting for halted, resolved and sync processes

- src/core.ts
> fix: allow default `killSignal` setting via env

- src/core.ts
- test/core.test.js
closes #1029
```js
try {
const p = $`exit 42`.nothrow()
await p.nothrow(false)
} catch ({ exitCode }) {
assert.equal(exitCode, 42)
}
```
> feat: make `nothrow()` toggleable

- .github/workflows/codeql.yml
- .github/workflows/dev-publish.yml
- .github/workflows/docs.yml
- .github/workflows/npm-publish.yml
- .github/workflows/osv.yml
- .github/workflows/test.yml
- package.json
> ci: apply zizmor suggestions

- src/cli.ts
- src/util.ts
> style(util): improve `formatCmd`

- test/core.test.js
- test/vendor.test.js
> test(core): check $ uses defaults store

- .github/workflows/osv.yml
* https://github.com/webpod/envapi/actions/runs/13058739080/job/36436234663#step:1:25
* https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> ci: update osv scanner action

- package-lock.json
- package.json
> fix: check user input on `dotenv.stringify`

- .size-limit.json
- src/core.ts
- test/core.test.js
> feat: protect `ProcessPromise` from inappropriate instantiation effects

- .size-limit.json
- src/core.ts
- src/util.ts
- test/core.test.js
- test/smoke/node.test.mjs
closes #1053
closes #1027
supersedes #1088
relates #984
```js
const o = new ProcessOutput({
store: {
stdall: ['foo\nba', 'r\nbaz'],
},
})
const lines = []
const expected = ['foo', 'bar', 'baz']
for (const line of o) {
lines.push(line)
}
assert.deepEqual(lines, expected)
assert.deepEqual(o.lines(), expected)
```
> feat: make `ProcessOutput` iterable

- .size-limit.json
- package-lock.json
- package.json
- scripts/build-dts.mjs
> perf(pkg): replace types deps with triple-spash refs

- docs/cli.md
- man/zx.1
- src/cli.ts
- test/cli.test.js
- test/export.test.js
- test/fixtures/non-std-ext.zx
resolves #1104
```bash
zx script.zx           # Unknown file extension "\.zx"
zx --ext=mjs script.zx # OK
```
> feat(cli): override non-js-like extensions via `--ext`

- .size-limit.json
- src/core.ts
- test/core.test.js
> feat: define primitive cast for `ProcessPromise` and `ProcessOutput`

- .size-limit.json
- src/core.ts
- src/goods.ts
- test/core.test.js
> feat: pass origin error as `ProcessOuput` cause

- .size-limit.json
- package-lock.json
- package.json
- src/cli.ts
- src/util.ts
- test/core.test.js
- test/util.test.js
closes #999
closes #1112
```js
const _$ = $({ prefix: '', postfix: '' })
const p1 = _$`echo ${['-n', 'foo']}`
assert.equal(p1.cmd, 'echo -n foo')
assert.equal((await p1).toString(), 'foo')
const p2 = _$`echo ${[1, '', '*', '2']}`
assert.equal(p2.cmd, `echo 1 $'' $'*' 2`)
assert.equal((await p2).toString(), `1  * 2\n`)
```
> fix: enhance quote to handle empty args

- .size-limit.json
- docs/configuration.md
- src/log.ts
- test/log.test.ts
continues #1122
```ts
$.log.formatters = {
cmd: (entry: LogEntry) => `CMD: ${entry.cmd}`,
fetch: (entry: LogEntry) => `FETCH: ${entry.url}`
}
```
> feat(log): provide custom formatting for every entry kind

- .size-limit.json
- docs/api.md
- src/goods.ts
- test/core.test.js
closes #977 
```js
const p1 = fetch('https://example.com').pipe($`cat`)
const p2 = fetch('https://example.com').pipe`cat`
```
> feat: introduce fetch pipe helper

- .size-limit.json
- src/cli.ts
- src/core.ts
- src/goods.ts
- test/goods.test.js
Restore CLI flags ~ envars symmetry.
```js
ZX_REGISTRY='https://custom-registry.example.com' zx script.js
```
> feat(cli): use `ZX_`-prefixed envars as default flags

- .size-limit.json
- docs/api.md
- src/vendor-extra.ts
- test/vendor.test.js
Fixes #1129
```js
const packages = glob.sync(['package.json', 'packages/*/package.json']);
```
> feat: re-export `glob.globbySync` as `glob.sync`

- .github/workflows/dev-publish.yml
- .github/workflows/jsr-publish.yml
- .github/workflows/publish.yml
> ci: enhance publish scripts

- .size-limit.json
- build/core.cjs
- src/core.ts
- test/core.test.js
> fix: handle `.nothrow()` option in `ProcessProcess[AsyncIterator]`

- .github/workflows/docs.yml
- .github/workflows/test.yml
> ci: use actions/upload-pages-artifact v4

- .github/workflows/test.yml
- .size-limit.json
- build/3rd-party-licenses
- build/index.cjs
- build/vendor-core.cjs
- build/vendor-core.d.ts
- package-lock.json
- package.json
- src/versions.ts
```
WMIC will be missing in Windows 11 25H2 (kernel >= 26000)
```
> feat: update `ps` utils to support Windows kernel >= 26000
